= Design Pattern - DP_name (DP_class)

TODO: A descriptive and unique name that helps in identifying and referring to the pattern.

Intent::

TODO: A description of the goal behind the pattern and the reason for using it.

Also Known As::

TODO: Other names for the pattern.

Motivation::

TODO: A scenario consisting of a problem and a context in which this pattern can be used.

Applicability::

TODO: Situations in which this pattern is usable; the context for the pattern.

Structure::

TODO: A graphical representation of the pattern.
Class diagrams and Interaction diagrams may be used for this purpose.

Participants::

TODO: A listing of the classes and objects used in the pattern and their roles in the design.

Collaboration::

TODO: A description of how classes and objects used in the pattern interact with each other.

Consequences::

TODO: A description of the results, side effects, and trade offs caused by using the pattern.

Implementation::

TODO: A description of an implementation of the pattern; the solution part of the pattern.

Sample Code::

TODO: An illustration of how the pattern can be used in a programming language.

Known Uses::

TODO: Examples of real usages of the pattern.

Related Patterns::

TODO: Other patterns that have some relationship with the pattern;
discussion of the differences between the pattern and similar patterns.

